"""Add tenant_id foreign key to invitations table

Revision ID: 6539c3fe626a
Revises: 8487352e991c
Create Date: 2025-07-07 03:56:27.157395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6539c3fe626a'
down_revision = '8487352e991c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'invitations', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invitations', type_='foreignkey')
    # ### end Alembic commands ### 