"""Add tenant_id foreign keys to all models

Revision ID: 8487352e991c
Revises: 4e75d9f52abd
Create Date: 2025-07-07 03:52:48.742293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8487352e991c'
down_revision = '4e75d9f52abd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'api_keys', 'tenants', ['tenant_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'audit_logs', 'tenants', ['tenant_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'identities', 'tenants', ['tenant_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'memories', 'tenants', ['tenant_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'policies', 'tenants', ['tenant_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'rate_limits', 'tenants', ['tenant_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'sessions', 'tenants', ['tenant_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'webhook_deliveries', 'tenants', ['tenant_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'webhooks', 'tenants', ['tenant_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'webhooks', type_='foreignkey')
    op.drop_constraint(None, 'webhook_deliveries', type_='foreignkey')
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.drop_constraint(None, 'rate_limits', type_='foreignkey')
    op.drop_constraint(None, 'policies', type_='foreignkey')
    op.drop_constraint(None, 'memories', type_='foreignkey')
    op.drop_constraint(None, 'identities', type_='foreignkey')
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.drop_constraint(None, 'api_keys', type_='foreignkey')
    # ### end Alembic commands ### 