"""add sso fields to identity

Revision ID: d1f881357f54
Revises: ae073a147d44
Create Date: 2025-07-05 22:49:51.374487

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = 'd1f881357f54'
down_revision = 'ae073a147d44'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('identities', sa.Column('sso_provider', sa.String(length=50), nullable=True))
    op.add_column('identities', sa.Column('sso_external_id', sa.String(length=255), nullable=True))
    op.add_column('identities', sa.Column('sso_email', sa.String(length=255), nullable=True))
    op.add_column('identities', sa.Column('sso_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index(op.f('ix_identities_sso_email'), 'identities', ['sso_email'], unique=False)
    op.create_index(op.f('ix_identities_sso_external_id'), 'identities', ['sso_external_id'], unique=False)
    op.create_index(op.f('ix_identities_sso_provider'), 'identities', ['sso_provider'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_identities_sso_provider'), table_name='identities')
    op.drop_index(op.f('ix_identities_sso_external_id'), table_name='identities')
    op.drop_index(op.f('ix_identities_sso_email'), table_name='identities')
    op.drop_column('identities', 'sso_metadata')
    op.drop_column('identities', 'sso_email')
    op.drop_column('identities', 'sso_external_id')
    op.drop_column('identities', 'sso_provider')
    # ### end Alembic commands ###
