"""Add tenant_id foreign key to identity_events table

Revision ID: f4b5c097ab35
Revises: 6539c3fe626a
Create Date: 2025-07-07 03:58:26.056028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4b5c097ab35'
down_revision = '6539c3fe626a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'identity_events', 'tenants', ['tenant_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'identity_events', type_='foreignkey')
    # ### end Alembic commands ### 